import type { Prisma, ReliabilityLevel, SourceBucket, SourceProvider, SourceType } from "@prisma/client";

interface DefaultSource {
  slug: string;
  name: string;
  url: string;
  feedUrl: string | null;
  provider: SourceProvider;
  type: SourceType;
  bucket: SourceBucket;
  sourceWeight: number;
  reliabilityLevel: ReliabilityLevel;
  enabled: boolean;
  config?: Prisma.InputJsonValue;
}

export const DEFAULT_SOURCES: DefaultSource[] = [
  {
    slug: "hf-trending-models",
    name: "Hugging Face Trending Models",
    url: "https://huggingface.co/models",
    feedUrl: null,
    provider: "HUGGINGFACE",
    type: "OFFICIAL",
    bucket: "PRACTICAL",
    sourceWeight: 1,
    reliabilityLevel: "HIGH",
    enabled: true,
    config: { entityType: "models", limit: 40 },
  },
  {
    slug: "hf-trending-spaces",
    name: "Hugging Face Trending Spaces",
    url: "https://huggingface.co/spaces",
    feedUrl: null,
    provider: "HUGGINGFACE",
    type: "OFFICIAL",
    bucket: "PRACTICAL",
    sourceWeight: 0.92,
    reliabilityLevel: "HIGH",
    enabled: true,
    config: { entityType: "spaces", limit: 30 },
  },
  {
    slug: "lmsys-chatbot-arena",
    name: "LMSYS Chatbot Arena",
    url: "https://lmarena.ai/",
    feedUrl: null,
    provider: "WEB",
    type: "RESEARCH",
    bucket: "PRACTICAL",
    sourceWeight: 0.9,
    reliabilityLevel: "MEDIUM",
    enabled: true,
  },
  {
    slug: "artificial-analysis",
    name: "Artificial Analysis",
    url: "https://artificialanalysis.ai/",
    feedUrl: null,
    provider: "WEB",
    type: "RESEARCH",
    bucket: "PRACTICAL",
    sourceWeight: 0.88,
    reliabilityLevel: "MEDIUM",
    enabled: true,
  },
  {
    slug: "openrouter-models",
    name: "OpenRouter Models",
    url: "https://openrouter.ai/models",
    feedUrl: null,
    provider: "OPENROUTER",
    type: "OFFICIAL",
    bucket: "PRACTICAL",
    sourceWeight: 0.9,
    reliabilityLevel: "HIGH",
    enabled: true,
  },
  {
    slug: "github-ai-trending",
    name: "GitHub AI Trending Repos",
    url: "https://github.com/trending",
    feedUrl: null,
    provider: "GITHUB_REPOS",
    type: "OFFICIAL",
    bucket: "PRACTICAL",
    sourceWeight: 0.9,
    reliabilityLevel: "HIGH",
    enabled: true,
    config: {
      query: "topic:artificial-intelligence stars:>300",
      limit: 30,
    },
  },
  {
    slug: "papers-with-code-latest",
    name: "Papers with Code Latest",
    url: "https://paperswithcode.com/latest",
    feedUrl: null,
    provider: "PAPERS_WITH_CODE",
    type: "RESEARCH",
    bucket: "PRACTICAL",
    sourceWeight: 0.85,
    reliabilityLevel: "HIGH",
    enabled: true,
    config: {
      limit: 30,
    },
  },
  {
    slug: "product-hunt-ai",
    name: "Product Hunt AI",
    url: "https://www.producthunt.com",
    feedUrl: "https://www.producthunt.com/feed",
    provider: "RSS",
    type: "OFFICIAL",
    bucket: "PRACTICAL",
    sourceWeight: 0.95,
    reliabilityLevel: "MEDIUM",
    enabled: true,
    config: {
      keywords: [
        "ai",
        "agent",
        "llm",
        "model",
        "automation",
        "workflow",
        "coding",
        "developer",
        "prompt",
      ],
      limit: 40,
    },
  },
  {
    slug: "reddit-localllama",
    name: "Reddit r/LocalLLaMA",
    url: "https://www.reddit.com/r/LocalLLaMA/",
    feedUrl: null,
    provider: "REDDIT_JSON",
    type: "MEDIA",
    bucket: "MEDIA",
    sourceWeight: 0.8,
    reliabilityLevel: "MEDIUM",
    enabled: true,
    config: {
      subreddit: "LocalLLaMA",
      sort: "hot",
      limit: 40,
    },
  },
  {
    slug: "reddit-localllm",
    name: "Reddit r/LocalLLM",
    url: "https://www.reddit.com/r/LocalLLM/",
    feedUrl: null,
    provider: "REDDIT_JSON",
    type: "MEDIA",
    bucket: "MEDIA",
    sourceWeight: 0.76,
    reliabilityLevel: "MEDIUM",
    enabled: true,
    config: {
      subreddit: "LocalLLM",
      sort: "hot",
      limit: 40,
    },
  },
  {
    slug: "social-researcher-feed-a",
    name: "Researcher Social Feed A",
    url: "https://social-agg-a.local",
    feedUrl: null,
    provider: "SOCIAL_AGG_A",
    type: "MEDIA",
    bucket: "MEDIA",
    sourceWeight: 0.6,
    reliabilityLevel: "MEDIUM",
    enabled: true,
    config: {
      watchlistId: "ai-researchers-global",
      providerType: "primary",
      minEngagement: 8,
      langAllow: ["en", "zh"],
      domainAllow: ["llm", "agent", "infra", "safety", "evaluation", "multimodal"],
      limit: 50,
    },
  },
  {
    slug: "social-researcher-feed-b",
    name: "Researcher Social Feed B",
    url: "https://social-agg-b.local",
    feedUrl: null,
    provider: "SOCIAL_AGG_B",
    type: "MEDIA",
    bucket: "MEDIA",
    sourceWeight: 0.5,
    reliabilityLevel: "MEDIUM",
    enabled: false,
    config: {
      watchlistId: "ai-researchers-global",
      providerType: "fallback",
      minEngagement: 8,
      langAllow: ["en", "zh"],
      domainAllow: ["llm", "agent", "infra", "safety", "evaluation", "multimodal"],
      limit: 50,
    },
  },
  {
    slug: "arxiv-ai",
    name: "arXiv AI",
    url: "https://arxiv.org",
    feedUrl: null,
    provider: "ARXIV",
    type: "RESEARCH",
    bucket: "PRACTICAL",
    sourceWeight: 0.82,
    reliabilityLevel: "HIGH",
    enabled: true,
    config: { searchQuery: "cat:cs.AI OR cat:cs.CL", limit: 30 },
  },
];
